### ISSUE TITLE
undefined method `define' for MagicLamp:Module

### ISSUE THREAD

**Issue by proubits** [crismali/magic_lamp#18]
Following the 'Drying up your fixtures' example showing on the readme, I got the error message as shown in the title. Here is my code
```ruby
#magic_lamp.rb
MagicLamp.define(controller: OrdersController) do
  fixture(name: "order_index") do
    @orders = Order.all
    render :index
  end
end
```
Anyone can help? thanks.

**Comment by crismali** [comment]
@proubits based on this and the other issue you opened (#19), it looks like you're using an older version of Magic Lamp. Check your `Gemfile.lock` or execute `MagicLamp::VERSION` in Rails console to find out the version you're using. The most recent version is `1.6.0`. Upgrading to that should solve these issues. 

Let me know how it goes.

**Comment by proubits** [comment]
Thanks for your reply. You are right. I am using 1.0.0. But I am not able to upgrade to 1.6.0 because of the dependency: rails (>=4.0.0). I am using rails 3.2. Is there any work around for this?

**Comment by crismali** [comment]
@proubits I've pushed up a branch (`potential_rails_3.2_support`). There's quite a bit of work to be done to make the tests compatible with Rails 3.2 through 4.2 (which is to say, I'm not sure how well the gem will work on Rails 3.2). But, you should be able to point to the branch in your Gemfile and see if resolves your issues.

**Comment by proubits** [comment]
Thanks for your quick fix. However it's not working well. I got the following error when I rake the lint task. 

```ruby
Error: NoMethodError: undefined method `key?' for :edit:Symbol
    /Users/dev/.rvm/gems/ruby-2.1.5@rails32/gems/activesupport-3.2.18/lib/active_support/core_ext/object/try.rb:36:in `try'
    /Users/dev/.rvm/gems/ruby-2.1.5@rails32/bundler/gems/magic_lamp-292501566b76/lib/magic_lamp/fixture_creator.rb:54:in `fetch_json_value'
    /Users/dev/.rvm/gems/ruby-2.1.5@rails32/bundler/gems/magic_lamp-292501566b76/lib/magic_lamp/fixture_creator.rb:41:in `fetch_rendered'
    /Users/dev/.rvm/gems/ruby-2.1.5@rails32/bundler/gems/magic_lamp-292501566b76/lib/magic_lamp/fixture_creator.rb:10:in `block in generate_template'
    /Users/dev/.rvm/gems/ruby-2.1.5@rails32/bundler/gems/magic_lamp-292501566b76/lib/magic_lamp/callbacks.rb:23:in `call'
    /Users/dev/.rvm/gems/ruby-2.1.5@rails32/bundler/gems/magic_lamp-292501566b76/lib/magic_lamp/callbacks.rb:23:in `execute_callbacks_around'
    /Users/dev/.rvm/gems/ruby-2.1.5@rails32/bundler/gems/magic_lamp-292501566b76/lib/magic_lamp/fixture_creator.rb:8:in `generate_template'
    /Users/dev/.rvm/gems/ruby-2.1.5@rails32/bundler/gems/magic_lamp-292501566b76/lib/magic_lamp.rb:101:in `generate_fixture'
    /Users/dev/.rvm/gems/ruby-2.1.5@rails32/bundler/gems/magic_lamp-292501566b76/lib/magic_lamp.rb:81:in `block in lint_fixtures'
    /Users/dev/.rvm/gems/ruby-2.1.5@rails32/bundler/gems/magic_lamp-292501566b76/lib/magic_lamp.rb:79:in `each'
    /Users/dev/.rvm/gems/ruby-2.1.5@rails32/bundler/gems/magic_lamp-292501566b76/lib/magic_lamp.rb:79:in `lint_fixtures'
    /Users/dev/.rvm/gems/ruby-2.1.5@rails32/bundler/gems/magic_lamp-292501566b76/lib/tasks/lint.rb:52:in `block (4 levels) in <top (required)>'
```

**Comment by crismali** [comment]
Hmm, looks like the implementation of `try` varies between Rails 3.2 and 4.0 

It looks like your fixture contains `render :edit`? Try `render template: :edit`. That should at least move you past this error.

**Comment by proubits** [comment]
Thanks. Tried what you suggested, got a new error.
```ruby
undefined method `sub!' for :index:Symbol
/Users/dev/.rvm/gems/ruby-2.1.5@rails32/gems/actionpack-3.2.18/lib/action_controller/metal/compatibility.rb:49:in `render_to_body'
/Users/dev/.rvm/gems/ruby-2.1.5@rails32/gems/actionpack-3.2.18/lib/abstract_controller/rendering.rb:96:in `render_to_string'
/Users/dev/.rvm/gems/ruby-2.1.5@rails32/gems/actionpack-3.2.18/lib/action_controller/metal/rendering.rb:23:in `render_to_string'
/Users/dev/.rvm/gems/ruby-2.1.5@rails32/gems/magic_lamp-1.0.0/lib/magic_lamp/fixture_creator.rb:11:in `generate_template'
/Users/dev/.rvm/gems/ruby-2.1.5@rails32/gems/magic_lamp-1.0.0/lib/magic_lamp.rb:79:in `generate_fixture'
/Users/dev/.rvm/gems/ruby-2.1.5@rails32/gems/magic_lamp-1.0.0/lib/magic_lamp.rb:85:in `block in generate_all_fixtures'
/Users/dev/.rvm/gems/ruby-2.1.5@rails32/gems/magic_lamp-1.0.0/lib/magic_lamp.rb:84:in `each'
/Users/dev/.rvm/gems/ruby-2.1.5@rails32/gems/magic_lamp-1.0.0/lib/magic_lamp.rb:84:in `each_with_object'
/Users/dev/.rvm/gems/ruby-2.1.5@rails32/gems/magic_lamp-1.0.0/lib/magic_lamp.rb:84:in `generate_all_fixtures'
/Users/dev/.rvm/gems/ruby-2.1.5@rails32/gems/magic_lamp-1.0.0/lib/tasks/lint_task.rb:5:in `block (2 levels) in <top (required)>'
Tasks: TOP => magic_lamp:lint
```

**Comment by crismali** [comment]
@proubits, it looks like the fixture in question calls `render template: :index`? Try changing that to `render template: "index"`. It seems Rails 3.2 is much pickier about strings vs symbols.

**Comment by proubits** [comment]
Thanks. That works. rake the lint task successfully.

However, I encountered another problem, which not related to this topic. I will open a new issue.

Thanks a lot for your help.
